### ISSUE TITLE
Issue Tracking on GeoGit Layers

### ISSUE THREAD

**Issue by ScottEvil** [ROGUE-JCTD/rogue_geonode#35]
As a user I need to be able to create, edit, and close issues on layers so that I can share with others the areas in the layer that need to be worked on.
- [ ] Create an issue for a layer
- [ ] Draw a polygon to associate to that issue
- [ ] Ability to assign an issue to a GeoNode user
- [ ] Register a FeatureType in GeoGit as a issue layer with GeoNode
